// Package genimportmap generates the per-consumer importmap Go source file —
// one `const <Group> = "..."` per group declared in package.json#tspkg.groups
// (plus the implicit default group, "Base").
package genimportmap

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"go.flaticols.dev/tspkg/internal/resolve"
)

// defaultGroup is the variable name (and the comment label) used for packages
// not listed in any user-defined group.
const defaultGroup = "Base"

// Generate writes a Go source file at outPath defining `package <packageName>`
// with one `const <Group> = "..."` per group. Packages not listed in any
// group land in the default `Base` const. groups maps user-facing group name
// → list of package names (typically read from package.json#tspkg.groups).
func Generate(resolved map[string]*resolve.Resolved, vendorURLPrefix, outPath, packageName string, groups map[string][]string) error {
	pkgGroup := pkgGroupIndex(groups)

	imports := map[string]map[string]string{}
	for name, r := range resolved {
		group := pkgGroup[name]
		if group == "" {
			group = defaultGroup
		}
		bucket, ok := imports[group]
		if !ok {
			bucket = map[string]string{}
			imports[group] = bucket
		}
		for sub, file := range r.Subpaths {
			specifier := name
			if sub != "." {
				specifier = name + strings.TrimPrefix(sub, ".")
			}
			bucket[specifier] = vendorURLPrefix + "/" + name + "/" + file
		}
	}

	src := buildSource(imports, sortedKeys(resolved), packageName)
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("importmap: gofmt: %w\n%s", err, src)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("importmap: mkdir %s: %w", filepath.Dir(outPath), err)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("importmap: write %s: %w", outPath, err)
	}
	return nil
}

// pkgGroupIndex inverts the user-facing groups map into a package → group
// (Go-identifier) lookup. The Go identifier is the group name title-cased so
// "graph" → "Graph" yields a public Go const.
func pkgGroupIndex(groups map[string][]string) map[string]string {
	idx := map[string]string{}
	for name, pkgs := range groups {
		ident := goIdent(name)
		for _, p := range pkgs {
			idx[p] = ident
		}
	}
	return idx
}

// goIdent maps a group name like "graph-heavy" → "GraphHeavy" so it can be
// used as a Go identifier. Empty names fall back to the default.
func goIdent(name string) string {
	if name == "" {
		return defaultGroup
	}
	out := strings.Builder{}
	upper := true
	for _, r := range name {
		if r == '-' || r == '_' || r == ' ' {
			upper = true
			continue
		}
		if upper {
			out.WriteRune(toUpper(r))
			upper = false
		} else {
			out.WriteRune(r)
		}
	}
	return out.String()
}

func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - ('a' - 'A')
	}
	return r
}

func buildSource(imports map[string]map[string]string, packageNames []string, packageName string) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tspkg. DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Resolved packages:\n")
	for _, n := range packageNames {
		fmt.Fprintf(&buf, "//   - %s\n", n)
	}
	buf.WriteString("\n")
	fmt.Fprintf(&buf, "package %s\n\n", packageName)

	groups := sortedKeys(imports)
	// Emit Base first (when present), then the rest alphabetically — a stable
	// order that puts the always-needed map at the top of the generated file.
	groups = baseFirst(groups)

	for _, group := range groups {
		entries := imports[group]
		doc := struct {
			Imports map[string]string `json:"imports"`
		}{Imports: entries}
		pretty, err := json.MarshalIndent(doc, "", "  ")
		if err != nil {
			// Plain string keys/values; marshalling cannot fail in practice.
			pretty = []byte(`{"imports":{}}`)
		}
		fmt.Fprintf(&buf, "// %s import map.\nconst %s = `%s`\n\n", group, group, string(pretty))
	}
	return buf.Bytes()
}

func baseFirst(keys []string) []string {
	out := make([]string, 0, len(keys))
	for _, k := range keys {
		if k == defaultGroup {
			out = append(out, k)
		}
	}
	for _, k := range keys {
		if k != defaultGroup {
			out = append(out, k)
		}
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
